### ISSUE TITLE
add automated tests

### ISSUE THREAD

**Issue by sibelius** [FogelAI/babel-plugin-transform-barrels#3]
make sure the code works

make sure we won't regress when adding or refactoring code

**Comment by FogelAI** [comment]
Hi @sibelius
Thank you for opening this issue and bringing this to my attention.
I have now implemented automated tests.

**Comment by FogelAI** [comment]
Hi @sibelius
Thank you for opening this issue and bringing this to my attention.
I have now implemented automated tests.
